# Generated by Django 2.2.14 on 2020-12-04 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='In Progress', max_length=250),
        ),
    ]
